import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavbarMain from "@/app/Componants/Navbar/NavbarMain"
import Footer from "@/app/Componants/Footer"
import { Poppins } from "next/font/google";


const poppins = Poppins({
  subsets: ["latin"], // Specify subsets
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins", // Custom variable name
  display: "swap", // Font display strategy
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=optional"
        />

      </head>
      <body className={`${poppins.variable} antialiased`}>
        <NavbarMain />

        {children}
        <Footer />
      </body>
    </html>
  );
}
